// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: actuals.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const actualsMoMDelta = `-- name: ActualsMoMDelta :many
WITH prev AS MATERIALIZED (
    SELECT ea.costcenter_id, SUM(ea.fte) AS total_fte
    FROM   employee_actuals ea
    WHERE  ea.import_run_id = $1
    GROUP  BY ea.costcenter_id
),
curr AS MATERIALIZED (
    SELECT ea.costcenter_id, SUM(ea.fte) AS total_fte
    FROM   employee_actuals ea
    WHERE  ea.import_run_id = $2
    GROUP  BY ea.costcenter_id
)
SELECT
    COALESCE(curr.costcenter_id, prev.costcenter_id) AS costcenter_id,
    prev.total_fte                                   AS prev_fte,
    curr.total_fte                                   AS curr_fte,
    COALESCE(curr.total_fte, 0) - COALESCE(prev.total_fte, 0) AS delta_fte
FROM  curr
FULL  OUTER JOIN prev ON curr.costcenter_id = prev.costcenter_id
ORDER BY COALESCE(curr.costcenter_id, prev.costcenter_id)
`

type ActualsMoMDeltaParams struct {
	PrevRunID uuid.UUID `json:"prev_run_id"`
	CurrRunID uuid.UUID `json:"curr_run_id"`
}

type ActualsMoMDeltaRow struct {
	CostcenterID uuid.UUID `json:"costcenter_id"`
	PrevFte      *int64    `json:"prev_fte"`
	CurrFte      *int64    `json:"curr_fte"`
	DeltaFte     int32     `json:"delta_fte"`
}

// Month-over-month delta per costcenter between two import runs.
// Covers the comparison: "last actual month vs current actual month".
//
// Returns one row per costcenter that appears in either run.
// Rows present only in prev_run_id have curr_fte = NULL (new leaver).
// Rows present only in curr_run_id have prev_fte = NULL (new joiner).
//
// PERFORMANCE NOTE (PG18)
// Each CTE is a simple aggregation on import_run_id + costcenter_id,
// hitting idx_employee_actuals_run_cc.  PG18 parallel aggregation can
// execute both CTEs concurrently when the planner chooses parallel mode.
// Mark both CTEs MATERIALIZED so the planner runs each exactly once
// rather than trying to merge them into a single scan.
func (q *Queries) ActualsMoMDelta(ctx context.Context, arg ActualsMoMDeltaParams) ([]ActualsMoMDeltaRow, error) {
	rows, err := q.db.Query(ctx, actualsMoMDelta, arg.PrevRunID, arg.CurrRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActualsMoMDeltaRow{}
	for rows.Next() {
		var i ActualsMoMDeltaRow
		if err := rows.Scan(
			&i.CostcenterID,
			&i.PrevFte,
			&i.CurrFte,
			&i.DeltaFte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const actualsRollupByCC = `-- name: ActualsRollupByCC :many
SELECT
    ea.costcenter_id,
    SUM(ea.fte)    AS total_fte,
    COUNT(*)       AS headcount
FROM  employee_actuals ea
WHERE ea.import_run_id = $1
GROUP BY ea.costcenter_id
ORDER BY ea.costcenter_id
`

type ActualsRollupByCCRow struct {
	CostcenterID uuid.UUID `json:"costcenter_id"`
	TotalFte     int64     `json:"total_fte"`
	Headcount    int64     `json:"headcount"`
}

// Sums FTE and headcount per costcenter for a single import run.
// Used for the "Actuals" column set in the WebUI table.
//
// PLAN: idx_employee_actuals_run_cc (import_run_id, costcenter_id) is a
// covering index for the GROUP BY — PostgreSQL can aggregate without a
// heap fetch if the FTE column is included.  If the table grows very large,
// add INCLUDE (fte) to that index (analogous to migration 004).
func (q *Queries) ActualsRollupByCC(ctx context.Context, importRunID uuid.UUID) ([]ActualsRollupByCCRow, error) {
	rows, err := q.db.Query(ctx, actualsRollupByCC, importRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActualsRollupByCCRow{}
	for rows.Next() {
		var i ActualsRollupByCCRow
		if err := rows.Scan(&i.CostcenterID, &i.TotalFte, &i.Headcount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActualsForEmployee = `-- name: GetActualsForEmployee :many

SELECT
    ea.id,
    ir.period_year,
    ir.period_month,
    ea.first_name,
    ea.last_name,
    ea.costcenter_id,
    ea.classification_id,
    ea.employee_group_id,
    ea.job_description,
    ea.fte
FROM  employee_actuals ea
JOIN  import_runs      ir ON ir.id = ea.import_run_id
WHERE ea.employee_id = $1
ORDER BY ir.period_year DESC, ir.period_month DESC
`

type GetActualsForEmployeeRow struct {
	ID               uuid.UUID       `json:"id"`
	PeriodYear       int16           `json:"period_year"`
	PeriodMonth      int16           `json:"period_month"`
	FirstName        string          `json:"first_name"`
	LastName         string          `json:"last_name"`
	CostcenterID     uuid.UUID       `json:"costcenter_id"`
	ClassificationID uuid.NullUUID   `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID   `json:"employee_group_id"`
	JobDescription   *string         `json:"job_description"`
	Fte              decimal.Decimal `json:"fte"`
}

// ── Actuals queries ───────────────────────────────────────────────────────────
// Full history of an employee across all import runs, newest first.
// Useful for the "employee detail" panel in the WebUI.
func (q *Queries) GetActualsForEmployee(ctx context.Context, employeeID uuid.UUID) ([]GetActualsForEmployeeRow, error) {
	rows, err := q.db.Query(ctx, getActualsForEmployee, employeeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActualsForEmployeeRow{}
	for rows.Next() {
		var i GetActualsForEmployeeRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.FirstName,
			&i.LastName,
			&i.CostcenterID,
			&i.ClassificationID,
			&i.EmployeeGroupID,
			&i.JobDescription,
			&i.Fte,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getImportRunByID = `-- name: GetImportRunByID :one
SELECT id, period_year, period_month, status, row_count, source_file, imported_by, imported_at
FROM   import_runs
WHERE  id = $1
`

func (q *Queries) GetImportRunByID(ctx context.Context, id uuid.UUID) (ImportRun, error) {
	row := q.db.QueryRow(ctx, getImportRunByID, id)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.Status,
		&i.RowCount,
		&i.SourceFile,
		&i.ImportedBy,
		&i.ImportedAt,
	)
	return i, err
}

const getImportRunByPeriod = `-- name: GetImportRunByPeriod :one
SELECT id, period_year, period_month, status, row_count, imported_by, imported_at
FROM   import_runs
WHERE  period_year  = $1
  AND  period_month = $2
`

type GetImportRunByPeriodParams struct {
	PeriodYear  int16 `json:"period_year"`
	PeriodMonth int16 `json:"period_month"`
}

type GetImportRunByPeriodRow struct {
	ID          uuid.UUID          `json:"id"`
	PeriodYear  int16              `json:"period_year"`
	PeriodMonth int16              `json:"period_month"`
	Status      string             `json:"status"`
	RowCount    *int32             `json:"row_count"`
	ImportedBy  uuid.UUID          `json:"imported_by"`
	ImportedAt  pgtype.Timestamptz `json:"imported_at"`
}

// Exact period lookup.  Used before an import to detect duplicate runs.
func (q *Queries) GetImportRunByPeriod(ctx context.Context, arg GetImportRunByPeriodParams) (GetImportRunByPeriodRow, error) {
	row := q.db.QueryRow(ctx, getImportRunByPeriod, arg.PeriodYear, arg.PeriodMonth)
	var i GetImportRunByPeriodRow
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.Status,
		&i.RowCount,
		&i.ImportedBy,
		&i.ImportedAt,
	)
	return i, err
}

const getLatestCompletedImportRun = `-- name: GetLatestCompletedImportRun :one
SELECT id, period_year, period_month, row_count, imported_at
FROM   import_runs
WHERE  status = 'completed'
ORDER  BY period_year DESC, period_month DESC
LIMIT  1
`

type GetLatestCompletedImportRunRow struct {
	ID          uuid.UUID          `json:"id"`
	PeriodYear  int16              `json:"period_year"`
	PeriodMonth int16              `json:"period_month"`
	RowCount    *int32             `json:"row_count"`
	ImportedAt  pgtype.Timestamptz `json:"imported_at"`
}

// Returns the most recent successfully completed import.
// Driving query for "current actual month" comparisons.
//
// PLAN: idx_import_runs_status filters to 'completed', then a sort on
// (period_year DESC, period_month DESC) with LIMIT 1 is cheap because
// import_runs has at most ~120 rows after 10 years of monthly imports.
func (q *Queries) GetLatestCompletedImportRun(ctx context.Context) (GetLatestCompletedImportRunRow, error) {
	row := q.db.QueryRow(ctx, getLatestCompletedImportRun)
	var i GetLatestCompletedImportRunRow
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.RowCount,
		&i.ImportedAt,
	)
	return i, err
}

const insertEmployeeActual = `-- name: InsertEmployeeActual :one

INSERT INTO employee_actuals (
    id,
    import_run_id,
    employee_id,
    first_name,
    last_name,
    costcenter_id,
    classification_id,
    employee_group_id,
    job_description,
    fte
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, import_run_id, employee_id, first_name, last_name, costcenter_id, classification_id, employee_group_id, job_description, fte, created_at
`

type InsertEmployeeActualParams struct {
	ImportRunID      uuid.UUID       `json:"import_run_id"`
	EmployeeID       uuid.UUID       `json:"employee_id"`
	FirstName        string          `json:"first_name"`
	LastName         string          `json:"last_name"`
	CostcenterID     uuid.UUID       `json:"costcenter_id"`
	ClassificationID uuid.NullUUID   `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID   `json:"employee_group_id"`
	JobDescription   *string         `json:"job_description"`
	Fte              decimal.Decimal `json:"fte"`
}

// ── employee_actuals insert (called in bulk via CopyFrom at import time) ──────
// Single-row variant used for testing and small corrections.
// For production imports, use pgx CopyFrom for bulk inserts instead.
func (q *Queries) InsertEmployeeActual(ctx context.Context, arg InsertEmployeeActualParams) (EmployeeActual, error) {
	row := q.db.QueryRow(ctx, insertEmployeeActual,
		arg.ImportRunID,
		arg.EmployeeID,
		arg.FirstName,
		arg.LastName,
		arg.CostcenterID,
		arg.ClassificationID,
		arg.EmployeeGroupID,
		arg.JobDescription,
		arg.Fte,
	)
	var i EmployeeActual
	err := row.Scan(
		&i.ID,
		&i.ImportRunID,
		&i.EmployeeID,
		&i.FirstName,
		&i.LastName,
		&i.CostcenterID,
		&i.ClassificationID,
		&i.EmployeeGroupID,
		&i.JobDescription,
		&i.Fte,
		&i.CreatedAt,
	)
	return i, err
}

const insertImportRun = `-- name: InsertImportRun :one



INSERT INTO import_runs (id, period_year, period_month, status, source_file, imported_by)
VALUES (
    gen_random_uuid(),
    $1,
    $2,
    'completed',
    $3,
    $4
)
RETURNING id, period_year, period_month, status, row_count, source_file, imported_by, imported_at
`

type InsertImportRunParams struct {
	PeriodYear  int16     `json:"period_year"`
	PeriodMonth int16     `json:"period_month"`
	SourceFile  *string   `json:"source_file"`
	ImportedBy  uuid.UUID `json:"imported_by"`
}

// ============================================================
// queries/actuals.sql
// SAP/Excel import tracking and employee_actuals queries.
//
// All employee_actuals rows are IMMUTABLE after insert.
// There are no UPDATE or DELETE queries in this file by design.
// ============================================================
// ── Import run management ─────────────────────────────────────────────────────
func (q *Queries) InsertImportRun(ctx context.Context, arg InsertImportRunParams) (ImportRun, error) {
	row := q.db.QueryRow(ctx, insertImportRun,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.SourceFile,
		arg.ImportedBy,
	)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.Status,
		&i.RowCount,
		&i.SourceFile,
		&i.ImportedBy,
		&i.ImportedAt,
	)
	return i, err
}

const listImportRuns = `-- name: ListImportRuns :many
SELECT id, period_year, period_month, status, row_count, imported_at
FROM   import_runs
ORDER  BY period_year DESC, period_month DESC
`

type ListImportRunsRow struct {
	ID          uuid.UUID          `json:"id"`
	PeriodYear  int16              `json:"period_year"`
	PeriodMonth int16              `json:"period_month"`
	Status      string             `json:"status"`
	RowCount    *int32             `json:"row_count"`
	ImportedAt  pgtype.Timestamptz `json:"imported_at"`
}

// Full history, newest first.
func (q *Queries) ListImportRuns(ctx context.Context) ([]ListImportRunsRow, error) {
	rows, err := q.db.Query(ctx, listImportRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListImportRunsRow{}
	for rows.Next() {
		var i ListImportRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.Status,
			&i.RowCount,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateImportRunRowCount = `-- name: UpdateImportRunRowCount :exec
UPDATE import_runs
SET    row_count = $1
WHERE  id = $2
`

type UpdateImportRunRowCountParams struct {
	RowCount *int32    `json:"row_count"`
	ID       uuid.UUID `json:"id"`
}

// Called after the bulk insert of employee_actuals to record the final count.
func (q *Queries) UpdateImportRunRowCount(ctx context.Context, arg UpdateImportRunRowCountParams) error {
	_, err := q.db.Exec(ctx, updateImportRunRowCount, arg.RowCount, arg.ID)
	return err
}
