// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costcenters.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getCostcenterByCode = `-- name: GetCostcenterByCode :one
SELECT id, code, name, level, parent_id, is_active
FROM   costcenters
WHERE  code = $1
`

type GetCostcenterByCodeRow struct {
	ID       uuid.UUID     `json:"id"`
	Code     string        `json:"code"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
	IsActive bool          `json:"is_active"`
}

func (q *Queries) GetCostcenterByCode(ctx context.Context, code string) (GetCostcenterByCodeRow, error) {
	row := q.db.QueryRow(ctx, getCostcenterByCode, code)
	var i GetCostcenterByCodeRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const getCostcenterByID = `-- name: GetCostcenterByID :one


SELECT id, code, name, level, parent_id, is_active
FROM   costcenters
WHERE  id = $1
`

type GetCostcenterByIDRow struct {
	ID       uuid.UUID     `json:"id"`
	Code     string        `json:"code"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
	IsActive bool          `json:"is_active"`
}

// ============================================================
// queries/costcenters.sql
// Hierarchy traversal and lookup queries for the costcenters table.
//
// PERFORMANCE NOTE (PG18)
// ───────────────────────
// WITH RECURSIVE queries are executed as a work-table scan in PostgreSQL.
// PG18 does not change the fundamental recursive CTE execution strategy,
// but the improved statistics and parallel query infrastructure help when
// the result set is large.
//
// For the typical hierarchy depth (3 levels, < 500 nodes total) these
// queries are fast regardless of PG version.  If the CC tree grows to
// thousands of nodes, consider materialising the full ancestry path as a
// ltree column (pg_catalog extension) to avoid recursion at query time.
// ============================================================
func (q *Queries) GetCostcenterByID(ctx context.Context, id uuid.UUID) (GetCostcenterByIDRow, error) {
	row := q.db.QueryRow(ctx, getCostcenterByID, id)
	var i GetCostcenterByIDRow
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Level,
		&i.ParentID,
		&i.IsActive,
	)
	return i, err
}

const getCostcenterDescendants = `-- name: GetCostcenterDescendants :many


WITH RECURSIVE descendants AS (
    SELECT cc.id, cc.code, cc.name, cc.level, cc.parent_id
    FROM   costcenters cc
    WHERE  cc.id        = $1
      AND  cc.is_active = true

    UNION ALL

    SELECT c.id, c.code, c.name, c.level, c.parent_id
    FROM   costcenters  c
    JOIN   descendants  d ON d.id = c.parent_id
    WHERE  c.is_active  = true
)
SELECT id, code, name, level, parent_id
FROM   descendants
ORDER  BY level, code
`

type GetCostcenterDescendantsRow struct {
	ID       uuid.UUID     `json:"id"`
	Code     string        `json:"code"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

// sorts naturally: parent names first, then children alphabetically
// Returns all active descendants of root_id, including root_id itself.
// Used to scope a report to a sub-tree (e.g. all CCs under a given department).
//
// PLAN: one recursive scan starting from a single row; each step hits
// idx_costcenters_parent_id.  For a 3-level tree this is at most 3 iterations.
func (q *Queries) GetCostcenterDescendants(ctx context.Context, rootID uuid.UUID) ([]GetCostcenterDescendantsRow, error) {
	rows, err := q.db.Query(ctx, getCostcenterDescendants, rootID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostcenterDescendantsRow{}
	for rows.Next() {
		var i GetCostcenterDescendantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCostcenterTree = `-- name: GetCostcenterTree :many
WITH RECURSIVE tree AS (
    -- Anchor: root nodes (no parent)
    SELECT
        id,
        code,
        name,
        level,
        parent_id,
        ARRAY[id]   AS path_ids,
        ARRAY[name] AS path_names,
        0           AS depth
    FROM costcenters
    WHERE parent_id IS NULL
      AND is_active  = true

    UNION ALL

    -- Recursion: children of the previously found set
    SELECT
        c.id,
        c.code,
        c.name,
        c.level,
        c.parent_id,
        t.path_ids   || c.id,
        t.path_names || c.name,
        t.depth + 1
    FROM costcenters  c
    JOIN tree         t ON t.id = c.parent_id
    WHERE c.is_active = true
)
SELECT
    id,
    code,
    name,
    level,
    parent_id,
    path_ids,
    path_names,
    depth
FROM  tree
ORDER BY path_names
`

type GetCostcenterTreeRow struct {
	ID        uuid.UUID     `json:"id"`
	Code      string        `json:"code"`
	Name      string        `json:"name"`
	Level     int16         `json:"level"`
	ParentID  uuid.NullUUID `json:"parent_id"`
	PathIds   interface{}   `json:"path_ids"`
	PathNames interface{}   `json:"path_names"`
	Depth     int32         `json:"depth"`
}

// Returns the full active hierarchy as a flat list, each row annotated
// with its ancestor path so the UI can reconstruct the tree without a
// second round-trip.
//
// path_ids   — ordered UUID array from root to this node (inclusive)
// path_names — parallel array of CC names, useful for breadcrumb display
// depth      — 0-based nesting depth (root = 0)
//
// PLAN: anchor scans costcenters on (parent_id IS NULL), then each
// recursive step uses idx_costcenters_parent_id for a fast index lookup.
func (q *Queries) GetCostcenterTree(ctx context.Context) ([]GetCostcenterTreeRow, error) {
	rows, err := q.db.Query(ctx, getCostcenterTree)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCostcenterTreeRow{}
	for rows.Next() {
		var i GetCostcenterTreeRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.ParentID,
			&i.PathIds,
			&i.PathNames,
			&i.Depth,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveCostcenters = `-- name: ListActiveCostcenters :many
SELECT id, code, name, level, parent_id
FROM   costcenters
WHERE  is_active = true
ORDER  BY level, code
`

type ListActiveCostcentersRow struct {
	ID       uuid.UUID     `json:"id"`
	Code     string        `json:"code"`
	Name     string        `json:"name"`
	Level    int16         `json:"level"`
	ParentID uuid.NullUUID `json:"parent_id"`
}

// Flat list of all active CCs ordered by level then code.
// Used to populate dropdowns; no hierarchy traversal needed.
func (q *Queries) ListActiveCostcenters(ctx context.Context) ([]ListActiveCostcentersRow, error) {
	rows, err := q.db.Query(ctx, listActiveCostcenters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveCostcentersRow{}
	for rows.Next() {
		var i ListActiveCostcentersRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Level,
			&i.ParentID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
