// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forecast_versions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveForecastVersion = `-- name: ArchiveForecastVersion :one
UPDATE forecast_versions
SET
    status      = 'archived',
    archived_at = now(),
    archived_by = $1
WHERE  id     = $2
  AND  status = 'working'
RETURNING id, label, status, period_year, period_month, fc_horizon_months, source_version_id, archived_at, archived_by, created_by, created_at
`

type ArchiveForecastVersionParams struct {
	ArchivedBy uuid.NullUUID `json:"archived_by"`
	ID         uuid.UUID     `json:"id"`
}

// Transitions the working version to archived.
// The chk_fv_archived_consistency constraint guarantees that archived_at
// and archived_by are either both set or both NULL — this UPDATE sets both.
// Returns the updated row so the caller can record the new archived_at.
//
// The WHERE status = 'working' guard prevents accidental double-archiving.
func (q *Queries) ArchiveForecastVersion(ctx context.Context, arg ArchiveForecastVersionParams) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, archiveForecastVersion, arg.ArchivedBy, arg.ID)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.FcHorizonMonths,
		&i.SourceVersionID,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getForecastVersionByID = `-- name: GetForecastVersionByID :one
SELECT
    id, label, status,
    period_year, period_month, fc_horizon_months,
    source_version_id,
    archived_at, archived_by,
    created_by, created_at
FROM  forecast_versions
WHERE id = $1
`

func (q *Queries) GetForecastVersionByID(ctx context.Context, id uuid.UUID) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, getForecastVersionByID, id)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.FcHorizonMonths,
		&i.SourceVersionID,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getVersionChain = `-- name: GetVersionChain :many
WITH RECURSIVE chain AS MATERIALIZED (
    -- Anchor: the requested start version
    SELECT
        fv.id,
        fv.label,
        fv.status,
        fv.period_year,
        fv.period_month,
        fv.source_version_id,
        fv.archived_at,
        1 AS position
    FROM  forecast_versions fv
    WHERE fv.id = $1

    UNION ALL

    -- Recursion: follow source_version_id until NULL
    SELECT
        fv.id,
        fv.label,
        fv.status,
        fv.period_year,
        fv.period_month,
        fv.source_version_id,
        fv.archived_at,
        c.position + 1
    FROM  forecast_versions fv
    JOIN  chain             c ON c.source_version_id = fv.id
)
SELECT id, label, status, period_year, period_month, archived_at, position
FROM   chain
ORDER  BY position
`

type GetVersionChainRow struct {
	ID          uuid.UUID          `json:"id"`
	Label       string             `json:"label"`
	Status      string             `json:"status"`
	PeriodYear  int16              `json:"period_year"`
	PeriodMonth int16              `json:"period_month"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	Position    int32              `json:"position"`
}

// Walks the source_version_id singly-linked list from a given version
// back to the root (source_version_id IS NULL).
// Returns versions oldest-last, i.e. position 1 = the requested version.
//
// Use case: render the "version history" sidebar in the WebUI, or list
// all archived snapshots available for a comparison.
//
// PLAN: each recursive step hits idx_fc_versions_source with a single-key
// lookup.  The chain is at most ~24 nodes for a 2-year rolling forecast,
// so this is always fast.
//
// PERFORMANCE NOTE (PG18)
// MATERIALIZED is intentional: without it, PG12+ may try to inline the
// recursive CTE into the outer query.  Inlining a recursive CTE is not
// possible today, but the hint future-proofs the query against planner
// changes and makes the intent explicit.
func (q *Queries) GetVersionChain(ctx context.Context, startVersionID uuid.UUID) ([]GetVersionChainRow, error) {
	rows, err := q.db.Query(ctx, getVersionChain, startVersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetVersionChainRow{}
	for rows.Next() {
		var i GetVersionChainRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.ArchivedAt,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkingForecastVersion = `-- name: GetWorkingForecastVersion :one


SELECT id, label, period_year, period_month, fc_horizon_months, source_version_id, created_at
FROM   forecast_versions
WHERE  status = 'working'
LIMIT  1
`

type GetWorkingForecastVersionRow struct {
	ID              uuid.UUID          `json:"id"`
	Label           string             `json:"label"`
	PeriodYear      int16              `json:"period_year"`
	PeriodMonth     int16              `json:"period_month"`
	FcHorizonMonths int16              `json:"fc_horizon_months"`
	SourceVersionID uuid.NullUUID      `json:"source_version_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// ============================================================
// queries/forecast_versions.sql
// Version lifecycle management: create, archive, seed, diff chain.
// ============================================================
// There is at most one working version at any time (partial unique index
// uq_fc_versions_one_working enforces this at the DB level).
// Returns an error if no working version exists yet.
//
// PLAN: index scan on idx_fc_versions_status, then LIMIT 1.
func (q *Queries) GetWorkingForecastVersion(ctx context.Context) (GetWorkingForecastVersionRow, error) {
	row := q.db.QueryRow(ctx, getWorkingForecastVersion)
	var i GetWorkingForecastVersionRow
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.FcHorizonMonths,
		&i.SourceVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const insertForecastVersion = `-- name: InsertForecastVersion :one
INSERT INTO forecast_versions (
    id,
    label,
    status,
    period_year,
    period_month,
    fc_horizon_months,
    source_version_id,
    created_by
) VALUES (
    gen_random_uuid(),
    $1,
    'working',
    $2,
    $3,
    $4,
    $5,
    $6
)
RETURNING id, label, status, period_year, period_month, fc_horizon_months, source_version_id, archived_at, archived_by, created_by, created_at
`

type InsertForecastVersionParams struct {
	Label           string        `json:"label"`
	PeriodYear      int16         `json:"period_year"`
	PeriodMonth     int16         `json:"period_month"`
	FcHorizonMonths int16         `json:"fc_horizon_months"`
	SourceVersionID uuid.NullUUID `json:"source_version_id"`
	CreatedBy       uuid.UUID     `json:"created_by"`
}

// Creates a new working version.
// source_version_id is NULL only for the very first version ever created;
// in all subsequent months it points to the just-archived snapshot.
func (q *Queries) InsertForecastVersion(ctx context.Context, arg InsertForecastVersionParams) (ForecastVersion, error) {
	row := q.db.QueryRow(ctx, insertForecastVersion,
		arg.Label,
		arg.PeriodYear,
		arg.PeriodMonth,
		arg.FcHorizonMonths,
		arg.SourceVersionID,
		arg.CreatedBy,
	)
	var i ForecastVersion
	err := row.Scan(
		&i.ID,
		&i.Label,
		&i.Status,
		&i.PeriodYear,
		&i.PeriodMonth,
		&i.FcHorizonMonths,
		&i.SourceVersionID,
		&i.ArchivedAt,
		&i.ArchivedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listForecastVersions = `-- name: ListForecastVersions :many
SELECT
    id, label, status,
    period_year, period_month,
    source_version_id,
    archived_at, created_at
FROM  forecast_versions
ORDER BY period_year DESC, period_month DESC, created_at DESC
`

type ListForecastVersionsRow struct {
	ID              uuid.UUID          `json:"id"`
	Label           string             `json:"label"`
	Status          string             `json:"status"`
	PeriodYear      int16              `json:"period_year"`
	PeriodMonth     int16              `json:"period_month"`
	SourceVersionID uuid.NullUUID      `json:"source_version_id"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// All versions newest-first.  Used for the version picker in the WebUI.
func (q *Queries) ListForecastVersions(ctx context.Context) ([]ListForecastVersionsRow, error) {
	rows, err := q.db.Query(ctx, listForecastVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListForecastVersionsRow{}
	for rows.Next() {
		var i ListForecastVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.Status,
			&i.PeriodYear,
			&i.PeriodMonth,
			&i.SourceVersionID,
			&i.ArchivedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
