// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: forecast_entries.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const closeContainerForecastEntry = `-- name: CloseContainerForecastEntry :execrows
UPDATE forecast_entries
SET    valid_to = $1::DATE
WHERE  version_id   = $2
  AND  container_id = $3
  AND  valid_to    IS NULL
  AND  is_deleted   = false
`

type CloseContainerForecastEntryParams struct {
	ValidTo     pgtype.Date   `json:"valid_to"`
	VersionID   uuid.UUID     `json:"version_id"`
	ContainerID uuid.NullUUID `json:"container_id"`
}

// Step 1 for a planning container.
//
// PLAN: idx_fe_version_cont_open.
func (q *Queries) CloseContainerForecastEntry(ctx context.Context, arg CloseContainerForecastEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeContainerForecastEntry, arg.ValidTo, arg.VersionID, arg.ContainerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeEmployeeForecastEntry = `-- name: CloseEmployeeForecastEntry :execrows
UPDATE forecast_entries
SET    valid_to = $1::DATE
WHERE  version_id  = $2
  AND  employee_id = $3
  AND  valid_to   IS NULL
  AND  is_deleted  = false
`

type CloseEmployeeForecastEntryParams struct {
	ValidTo    pgtype.Date   `json:"valid_to"`
	VersionID  uuid.UUID     `json:"version_id"`
	EmployeeID uuid.NullUUID `json:"employee_id"`
}

// Step 1 of a change for a real employee: close the currently open row.
// valid_to is the first day of the month when the new state takes effect.
//
// Returns the number of rows updated (should always be 0 or 1).
// If 0 rows updated, no open row exists — the caller should insert without closing.
//
// PLAN: idx_fe_version_empl_open (version_id, employee_id)
// WHERE valid_to IS NULL AND is_deleted = false → single-row key lookup.
func (q *Queries) CloseEmployeeForecastEntry(ctx context.Context, arg CloseEmployeeForecastEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeEmployeeForecastEntry, arg.ValidTo, arg.VersionID, arg.EmployeeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const diffVersionsByCC = `-- name: DiffVersionsByCC :many

WITH version_a AS MATERIALIZED (
    SELECT fe.costcenter_id, SUM(fe.fte) AS total_fte
    FROM   forecast_entries fe
    WHERE  fe.version_id = $1
      AND  fe.is_deleted  = false
      AND  fe.valid_from <= $2::DATE
      AND  (fe.valid_to IS NULL OR fe.valid_to > $2::DATE)
    GROUP  BY fe.costcenter_id
),
version_b AS MATERIALIZED (
    SELECT fe.costcenter_id, SUM(fe.fte) AS total_fte
    FROM   forecast_entries fe
    WHERE  fe.version_id = $3
      AND  fe.is_deleted  = false
      AND  fe.valid_from <= $2::DATE
      AND  (fe.valid_to IS NULL OR fe.valid_to > $2::DATE)
    GROUP  BY fe.costcenter_id
)
SELECT
    COALESCE(a.costcenter_id, b.costcenter_id)      AS costcenter_id,
    a.total_fte                                      AS fte_version_a,
    b.total_fte                                      AS fte_version_b,
    COALESCE(b.total_fte, 0) - COALESCE(a.total_fte, 0) AS fte_delta
FROM  version_a a
FULL  OUTER JOIN version_b b ON a.costcenter_id = b.costcenter_id
WHERE a.total_fte IS DISTINCT FROM b.total_fte
ORDER BY COALESCE(a.costcenter_id, b.costcenter_id)
`

type DiffVersionsByCCParams struct {
	VersionAID uuid.UUID   `json:"version_a_id"`
	MonthStart pgtype.Date `json:"month_start"`
	VersionBID uuid.UUID   `json:"version_b_id"`
}

type DiffVersionsByCCRow struct {
	CostcenterID uuid.UUID `json:"costcenter_id"`
	FteVersionA  *int64    `json:"fte_version_a"`
	FteVersionB  *int64    `json:"fte_version_b"`
	FteDelta     int32     `json:"fte_delta"`
}

// ── Version diff ──────────────────────────────────────────────────────────────
// Compares total FTE per costcenter between two forecast versions for a
// single target month.  Returns only costcenters where the values differ.
//
// Use cases:
//   - Compare two archived snapshots (e.g. last month's FC vs this month's FC)
//   - Compare the working version against the previous snapshot
//
// BOTH CTEs are marked MATERIALIZED so the planner executes each exactly
// once against its respective version_id, using idx_fe_version_cc_from.
// Without MATERIALIZED, PG12+ may inline the CTEs; while that is safe here,
// it prevents the parallel execution hint that PG18 uses when both CTEs
// reference different version_ids (no shared data dependency).
//
// PERFORMANCE NOTE (PG18)
// PG18's improved parallel query infrastructure can run both CTE scans
// concurrently when max_parallel_workers_per_gather > 0 and the table is
// large enough to trigger parallelism.  MATERIALIZED makes the independence
// of the two scans explicit to the planner.
func (q *Queries) DiffVersionsByCC(ctx context.Context, arg DiffVersionsByCCParams) ([]DiffVersionsByCCRow, error) {
	rows, err := q.db.Query(ctx, diffVersionsByCC, arg.VersionAID, arg.MonthStart, arg.VersionBID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiffVersionsByCCRow{}
	for rows.Next() {
		var i DiffVersionsByCCRow
		if err := rows.Scan(
			&i.CostcenterID,
			&i.FteVersionA,
			&i.FteVersionB,
			&i.FteDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const diffVersionsByEmployee = `-- name: DiffVersionsByEmployee :many
WITH version_a AS MATERIALIZED (
    SELECT
        COALESCE(fe.employee_id::TEXT, fe.container_id::TEXT) AS subject_key,
        fe.employee_id,
        fe.container_id,
        fe.costcenter_id,
        fe.classification_id,
        fe.employee_group_id,
        fe.fte
    FROM  forecast_entries fe
    WHERE fe.version_id = $1
      AND fe.is_deleted  = false
      AND fe.valid_from <= $2::DATE
      AND (fe.valid_to IS NULL OR fe.valid_to > $2::DATE)
),
version_b AS MATERIALIZED (
    SELECT
        COALESCE(fe.employee_id::TEXT, fe.container_id::TEXT) AS subject_key,
        fe.employee_id,
        fe.container_id,
        fe.costcenter_id,
        fe.classification_id,
        fe.employee_group_id,
        fe.fte
    FROM  forecast_entries fe
    WHERE fe.version_id = $3
      AND fe.is_deleted  = false
      AND fe.valid_from <= $2::DATE
      AND (fe.valid_to IS NULL OR fe.valid_to > $2::DATE)
)
SELECT
    COALESCE(a.subject_key,      b.subject_key)      AS subject_key,
    COALESCE(a.employee_id,      b.employee_id)      AS employee_id,
    COALESCE(a.container_id,     b.container_id)     AS container_id,
    a.costcenter_id                                  AS costcenter_id_a,
    b.costcenter_id                                  AS costcenter_id_b,
    a.classification_id                              AS classification_id_a,
    b.classification_id                              AS classification_id_b,
    a.employee_group_id                              AS employee_group_id_a,
    b.employee_group_id                              AS employee_group_id_b,
    a.fte                                            AS fte_a,
    b.fte                                            AS fte_b,
    COALESCE(b.fte, 0) - COALESCE(a.fte, 0)         AS fte_delta
FROM  version_a a
FULL  OUTER JOIN version_b b ON a.subject_key = b.subject_key
WHERE a.costcenter_id     IS DISTINCT FROM b.costcenter_id
   OR a.classification_id IS DISTINCT FROM b.classification_id
   OR a.employee_group_id IS DISTINCT FROM b.employee_group_id
   OR a.fte               IS DISTINCT FROM b.fte
ORDER BY COALESCE(a.subject_key, b.subject_key)
`

type DiffVersionsByEmployeeParams struct {
	VersionAID uuid.UUID   `json:"version_a_id"`
	MonthStart pgtype.Date `json:"month_start"`
	VersionBID uuid.UUID   `json:"version_b_id"`
}

type DiffVersionsByEmployeeRow struct {
	SubjectKey        interface{}    `json:"subject_key"`
	EmployeeID        uuid.NullUUID  `json:"employee_id"`
	ContainerID       uuid.NullUUID  `json:"container_id"`
	CostcenterIDA     uuid.NullUUID  `json:"costcenter_id_a"`
	CostcenterIDB     uuid.NullUUID  `json:"costcenter_id_b"`
	ClassificationIDA uuid.NullUUID  `json:"classification_id_a"`
	ClassificationIDB uuid.NullUUID  `json:"classification_id_b"`
	EmployeeGroupIDA  uuid.NullUUID  `json:"employee_group_id_a"`
	EmployeeGroupIDB  uuid.NullUUID  `json:"employee_group_id_b"`
	FteA              pgtype.Numeric `json:"fte_a"`
	FteB              pgtype.Numeric `json:"fte_b"`
	FteDelta          int32          `json:"fte_delta"`
}

// Row-level diff between two versions for a given month.
// Returns every subject (employee or container) where any tracked attribute
// changed — costcenter_id, classification_id, employee_group_id, or fte.
//
// Rows present only in version A (employee left the FC) have *_b columns NULL.
// Rows present only in version B (employee added to FC) have *_a columns NULL.
//
// COALESCE join key: both employee_id and container_id are UUID, but a given
// subject only appears in one column per row (chk_fe_subject_exclusive).
// We cast both to TEXT for FULL OUTER JOIN — the cast is cheap, and UUID
// comparison is always by value so no false matches occur.
//
// PLAN: each CTE uses idx_fe_version_empl_from / idx_fe_version_cont_from
// (from migration 004) for index-only scans on the key columns.
func (q *Queries) DiffVersionsByEmployee(ctx context.Context, arg DiffVersionsByEmployeeParams) ([]DiffVersionsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, diffVersionsByEmployee, arg.VersionAID, arg.MonthStart, arg.VersionBID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DiffVersionsByEmployeeRow{}
	for rows.Next() {
		var i DiffVersionsByEmployeeRow
		if err := rows.Scan(
			&i.SubjectKey,
			&i.EmployeeID,
			&i.ContainerID,
			&i.CostcenterIDA,
			&i.CostcenterIDB,
			&i.ClassificationIDA,
			&i.ClassificationIDB,
			&i.EmployeeGroupIDA,
			&i.EmployeeGroupIDB,
			&i.FteA,
			&i.FteB,
			&i.FteDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveContainerForecastEntry = `-- name: GetActiveContainerForecastEntry :one
SELECT
    id,
    first_name, last_name,
    costcenter_id, classification_id, employee_group_id,
    job_description, fte,
    valid_from, valid_to
FROM  forecast_entries
WHERE version_id   = $1
  AND container_id = $2
  AND is_deleted   = false
  AND valid_from  <= $3::DATE
  AND (valid_to IS NULL OR valid_to > $3::DATE)
LIMIT 1
`

type GetActiveContainerForecastEntryParams struct {
	VersionID   uuid.UUID     `json:"version_id"`
	ContainerID uuid.NullUUID `json:"container_id"`
	MonthStart  pgtype.Date   `json:"month_start"`
}

type GetActiveContainerForecastEntryRow struct {
	ID               uuid.UUID       `json:"id"`
	FirstName        string          `json:"first_name"`
	LastName         string          `json:"last_name"`
	CostcenterID     uuid.UUID       `json:"costcenter_id"`
	ClassificationID uuid.NullUUID   `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID   `json:"employee_group_id"`
	JobDescription   *string         `json:"job_description"`
	Fte              decimal.Decimal `json:"fte"`
	ValidFrom        pgtype.Date     `json:"valid_from"`
	ValidTo          pgtype.Date     `json:"valid_to"`
}

// Same as above for planning containers.
//
// PLAN: idx_fe_version_cont_from.
func (q *Queries) GetActiveContainerForecastEntry(ctx context.Context, arg GetActiveContainerForecastEntryParams) (GetActiveContainerForecastEntryRow, error) {
	row := q.db.QueryRow(ctx, getActiveContainerForecastEntry, arg.VersionID, arg.ContainerID, arg.MonthStart)
	var i GetActiveContainerForecastEntryRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CostcenterID,
		&i.ClassificationID,
		&i.EmployeeGroupID,
		&i.JobDescription,
		&i.Fte,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getActiveEmployeeForecastEntry = `-- name: GetActiveEmployeeForecastEntry :one



SELECT
    id,
    first_name, last_name,
    costcenter_id, classification_id, employee_group_id,
    job_description, fte,
    valid_from, valid_to
FROM  forecast_entries
WHERE version_id  = $1
  AND employee_id = $2
  AND is_deleted  = false
  AND valid_from <= $3::DATE
  AND (valid_to IS NULL OR valid_to > $3::DATE)
LIMIT 1
`

type GetActiveEmployeeForecastEntryParams struct {
	VersionID  uuid.UUID     `json:"version_id"`
	EmployeeID uuid.NullUUID `json:"employee_id"`
	MonthStart pgtype.Date   `json:"month_start"`
}

type GetActiveEmployeeForecastEntryRow struct {
	ID               uuid.UUID       `json:"id"`
	FirstName        string          `json:"first_name"`
	LastName         string          `json:"last_name"`
	CostcenterID     uuid.UUID       `json:"costcenter_id"`
	ClassificationID uuid.NullUUID   `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID   `json:"employee_group_id"`
	JobDescription   *string         `json:"job_description"`
	Fte              decimal.Decimal `json:"fte"`
	ValidFrom        pgtype.Date     `json:"valid_from"`
	ValidTo          pgtype.Date     `json:"valid_to"`
}

// ============================================================
// queries/forecast_entries.sql
// SCD Type 2 operations, monthly rollup, and version diff.
//
// SCD PATTERN REMINDER
// ────────────────────
// Each attribute change is a two-step operation:
//  1. Close the current open row:  set valid_to = change_month.
//  2. Insert the new state:        valid_from = change_month, valid_to = NULL.
//
// "Active row for month M" predicate (used throughout):
//
//	valid_from <= M  AND  (valid_to IS NULL OR valid_to > M)  AND  is_deleted = false
//
// Employee and container entries use separate query pairs because the
// planner can then choose the appropriate partial index (empl vs cont).
// ============================================================
// ── Active-row lookups ────────────────────────────────────────────────────────
// Returns the single active row for a real employee in a given version and month.
//
// PLAN: idx_fe_version_empl_from (version_id, employee_id, valid_from)
// INCLUDE (valid_to, fte, costcenter_id, …) WHERE is_deleted = false.
// The index leaf page contains all projected columns → index-only scan.
func (q *Queries) GetActiveEmployeeForecastEntry(ctx context.Context, arg GetActiveEmployeeForecastEntryParams) (GetActiveEmployeeForecastEntryRow, error) {
	row := q.db.QueryRow(ctx, getActiveEmployeeForecastEntry, arg.VersionID, arg.EmployeeID, arg.MonthStart)
	var i GetActiveEmployeeForecastEntryRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.CostcenterID,
		&i.ClassificationID,
		&i.EmployeeGroupID,
		&i.JobDescription,
		&i.Fte,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const getAuditHistoryForEntry = `-- name: GetAuditHistoryForEntry :many

SELECT
    id,
    action,
    changed_fields,
    changed_by,
    changed_at,
    client_ip
FROM  forecast_entry_audit
WHERE forecast_entry_id = $1
ORDER BY changed_at DESC
`

type GetAuditHistoryForEntryRow struct {
	ID            uuid.UUID          `json:"id"`
	Action        string             `json:"action"`
	ChangedFields []byte             `json:"changed_fields"`
	ChangedBy     uuid.UUID          `json:"changed_by"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	ClientIp      *string            `json:"client_ip"`
}

// ── Audit history ─────────────────────────────────────────────────────────────
// Full change history for a single forecast_entries row, newest first.
// Used by the "change history" drawer in the UI.
func (q *Queries) GetAuditHistoryForEntry(ctx context.Context, forecastEntryID uuid.UUID) ([]GetAuditHistoryForEntryRow, error) {
	rows, err := q.db.Query(ctx, getAuditHistoryForEntry, forecastEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuditHistoryForEntryRow{}
	for rows.Next() {
		var i GetAuditHistoryForEntryRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.ChangedFields,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.ClientIp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAuditHistoryForVersion = `-- name: GetAuditHistoryForVersion :many
SELECT
    fea.id,
    fea.forecast_entry_id,
    fea.action,
    fea.changed_fields,
    fea.changed_by,
    fea.changed_at,
    fe.employee_id,
    fe.container_id,
    fe.costcenter_id
FROM  forecast_entry_audit fea
JOIN  forecast_entries     fe  ON fe.id = fea.forecast_entry_id
WHERE fea.version_id = $1
ORDER BY fea.changed_at DESC
LIMIT  $2::BIGINT
`

type GetAuditHistoryForVersionParams struct {
	VersionID uuid.UUID `json:"version_id"`
	LimitRows int64     `json:"limit_rows"`
}

type GetAuditHistoryForVersionRow struct {
	ID              uuid.UUID          `json:"id"`
	ForecastEntryID uuid.UUID          `json:"forecast_entry_id"`
	Action          string             `json:"action"`
	ChangedFields   []byte             `json:"changed_fields"`
	ChangedBy       uuid.UUID          `json:"changed_by"`
	ChangedAt       pgtype.Timestamptz `json:"changed_at"`
	EmployeeID      uuid.NullUUID      `json:"employee_id"`
	ContainerID     uuid.NullUUID      `json:"container_id"`
	CostcenterID    uuid.UUID          `json:"costcenter_id"`
}

// All changes made to a forecast version, newest first.
// Used by the "version activity log" panel.
// Limit to a reasonable page size in the application layer.
func (q *Queries) GetAuditHistoryForVersion(ctx context.Context, arg GetAuditHistoryForVersionParams) ([]GetAuditHistoryForVersionRow, error) {
	rows, err := q.db.Query(ctx, getAuditHistoryForVersion, arg.VersionID, arg.LimitRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAuditHistoryForVersionRow{}
	for rows.Next() {
		var i GetAuditHistoryForVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.ForecastEntryID,
			&i.Action,
			&i.ChangedFields,
			&i.ChangedBy,
			&i.ChangedAt,
			&i.EmployeeID,
			&i.ContainerID,
			&i.CostcenterID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertForecastEntry = `-- name: InsertForecastEntry :one

INSERT INTO forecast_entries (
    id,
    version_id,
    employee_id,
    container_id,
    first_name, last_name,
    costcenter_id, classification_id, employee_group_id,
    job_description, fte,
    valid_from,
    is_deleted,
    created_by
) VALUES (
    gen_random_uuid(),
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    false,
    $12
)
RETURNING id, version_id, employee_id, container_id, first_name, last_name, costcenter_id, classification_id, employee_group_id, job_description, fte, valid_from, valid_to, is_deleted, deleted_at, deleted_by, created_by, created_at
`

type InsertForecastEntryParams struct {
	VersionID        uuid.UUID       `json:"version_id"`
	EmployeeID       uuid.NullUUID   `json:"employee_id"`
	ContainerID      uuid.NullUUID   `json:"container_id"`
	FirstName        string          `json:"first_name"`
	LastName         string          `json:"last_name"`
	CostcenterID     uuid.UUID       `json:"costcenter_id"`
	ClassificationID uuid.NullUUID   `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID   `json:"employee_group_id"`
	JobDescription   *string         `json:"job_description"`
	Fte              decimal.Decimal `json:"fte"`
	ValidFrom        pgtype.Date     `json:"valid_from"`
	CreatedBy        uuid.UUID       `json:"created_by"`
}

// ── SCD Type 2 write operations ───────────────────────────────────────────────
// Step 2 of a change: insert the new attribute state.
// valid_to is NULL for the new open-ended row.
// Always pair with CloseEmployee/ContainerForecastEntry (step 1) unless
// this is the very first entry for the subject in this version.
func (q *Queries) InsertForecastEntry(ctx context.Context, arg InsertForecastEntryParams) (ForecastEntry, error) {
	row := q.db.QueryRow(ctx, insertForecastEntry,
		arg.VersionID,
		arg.EmployeeID,
		arg.ContainerID,
		arg.FirstName,
		arg.LastName,
		arg.CostcenterID,
		arg.ClassificationID,
		arg.EmployeeGroupID,
		arg.JobDescription,
		arg.Fte,
		arg.ValidFrom,
		arg.CreatedBy,
	)
	var i ForecastEntry
	err := row.Scan(
		&i.ID,
		&i.VersionID,
		&i.EmployeeID,
		&i.ContainerID,
		&i.FirstName,
		&i.LastName,
		&i.CostcenterID,
		&i.ClassificationID,
		&i.EmployeeGroupID,
		&i.JobDescription,
		&i.Fte,
		&i.ValidFrom,
		&i.ValidTo,
		&i.IsDeleted,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listActiveEntriesForVersion = `-- name: ListActiveEntriesForVersion :many
SELECT
    id,
    employee_id, container_id,
    first_name, last_name,
    costcenter_id, classification_id, employee_group_id,
    job_description, fte,
    valid_from, valid_to
FROM  forecast_entries
WHERE version_id  = $1
  AND is_deleted  = false
  AND valid_from <= $2::DATE
  AND (valid_to IS NULL OR valid_to > $2::DATE)
ORDER BY employee_id NULLS LAST, container_id NULLS LAST
`

type ListActiveEntriesForVersionParams struct {
	VersionID  uuid.UUID   `json:"version_id"`
	MonthStart pgtype.Date `json:"month_start"`
}

type ListActiveEntriesForVersionRow struct {
	ID               uuid.UUID       `json:"id"`
	EmployeeID       uuid.NullUUID   `json:"employee_id"`
	ContainerID      uuid.NullUUID   `json:"container_id"`
	FirstName        string          `json:"first_name"`
	LastName         string          `json:"last_name"`
	CostcenterID     uuid.UUID       `json:"costcenter_id"`
	ClassificationID uuid.NullUUID   `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID   `json:"employee_group_id"`
	JobDescription   *string         `json:"job_description"`
	Fte              decimal.Decimal `json:"fte"`
	ValidFrom        pgtype.Date     `json:"valid_from"`
	ValidTo          pgtype.Date     `json:"valid_to"`
}

// All active entries (employees + containers) in a version for a given month.
// Used to seed the next working version at month rollover.
//
// PLAN: idx_fe_version_valid_from (version_id, valid_from) for the range scan;
// heap access for the remaining columns.  For the seed operation this full
// scan is expected and unavoidable — it runs once per month.
func (q *Queries) ListActiveEntriesForVersion(ctx context.Context, arg ListActiveEntriesForVersionParams) ([]ListActiveEntriesForVersionRow, error) {
	rows, err := q.db.Query(ctx, listActiveEntriesForVersion, arg.VersionID, arg.MonthStart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveEntriesForVersionRow{}
	for rows.Next() {
		var i ListActiveEntriesForVersionRow
		if err := rows.Scan(
			&i.ID,
			&i.EmployeeID,
			&i.ContainerID,
			&i.FirstName,
			&i.LastName,
			&i.CostcenterID,
			&i.ClassificationID,
			&i.EmployeeGroupID,
			&i.JobDescription,
			&i.Fte,
			&i.ValidFrom,
			&i.ValidTo,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const monthlyForecastRollupByCC = `-- name: MonthlyForecastRollupByCC :many

SELECT
    gs.month_start::DATE                AS month_start,
    fe.costcenter_id,
    SUM(fe.fte)                         AS total_fte,
    COUNT(*)::BIGINT                    AS headcount
FROM generate_series(
    $1::TIMESTAMPTZ,
    $2::TIMESTAMPTZ,
    '1 month'::INTERVAL
) AS gs(month_start)
CROSS JOIN LATERAL (
    SELECT costcenter_id, fte
    FROM   forecast_entries
    WHERE  version_id  = $3
      AND  is_deleted  = false
      AND  valid_from <= gs.month_start::DATE
      AND  (valid_to IS NULL OR valid_to > gs.month_start::DATE)
) AS fe
GROUP BY gs.month_start, fe.costcenter_id
ORDER BY gs.month_start, fe.costcenter_id
`

type MonthlyForecastRollupByCCParams struct {
	FcStartMonth pgtype.Timestamptz `json:"fc_start_month"`
	FcEndMonth   pgtype.Timestamptz `json:"fc_end_month"`
	VersionID    uuid.UUID          `json:"version_id"`
}

type MonthlyForecastRollupByCCRow struct {
	MonthStart   pgtype.Date `json:"month_start"`
	CostcenterID uuid.UUID   `json:"costcenter_id"`
	TotalFte     int64       `json:"total_fte"`
	Headcount    int64       `json:"headcount"`
}

// ── Monthly rollup (WebUI table — the most critical query) ────────────────────
// Returns total FTE and headcount per costcenter per month for a version.
// This drives the main WebUI table: rows = costcenters, columns = months.
//
// PARAMETERS
//
//	version_id     — which forecast version to read
//	fc_start_month — first month of the grid  (first day of month, e.g. 2025-01-01)
//	fc_end_month   — last  month of the grid  (first day of month, e.g. 2026-06-01)
//
// QUERY STRATEGY
// generate_series produces one row per month.  The CROSS JOIN LATERAL
// tells the planner to execute the subquery independently for each month
// value, which allows index-only scans on idx_fe_version_cc_from for each
// (version_id, *, valid_from) prefix.
//
// Without LATERAL the planner might choose a hash join across all months
// simultaneously, which forces a full scan of forecast_entries for the
// version — far more expensive when only the last few months have changes.
//
// PERFORMANCE NOTE (PG18)
// ───────────────────────
// idx_fe_version_cc_from (from migration 004) now includes valid_to and fte
// via INCLUDE, making this a fully index-only scan — no heap access at all.
//
// PG18 async I/O reduces heap-fetch latency when the index is cold (first
// query after restart).  For warm-cache production queries the INCLUDE
// strategy is what matters most.
//
// headcount counts all rows (including containers with FTE > 1 or < 0).
// If you want headcount to count only positive-FTE employees, add a WHERE
// clause inside the subquery: AND fte > 0 AND employee_id IS NOT NULL.
func (q *Queries) MonthlyForecastRollupByCC(ctx context.Context, arg MonthlyForecastRollupByCCParams) ([]MonthlyForecastRollupByCCRow, error) {
	rows, err := q.db.Query(ctx, monthlyForecastRollupByCC, arg.FcStartMonth, arg.FcEndMonth, arg.VersionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MonthlyForecastRollupByCCRow{}
	for rows.Next() {
		var i MonthlyForecastRollupByCCRow
		if err := rows.Scan(
			&i.MonthStart,
			&i.CostcenterID,
			&i.TotalFte,
			&i.Headcount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteContainerForecastEntry = `-- name: SoftDeleteContainerForecastEntry :exec
UPDATE forecast_entries
SET
    is_deleted = true,
    deleted_at = now(),
    deleted_by = $1
WHERE version_id   = $2
  AND container_id = $3
  AND valid_to    IS NULL
  AND is_deleted   = false
`

type SoftDeleteContainerForecastEntryParams struct {
	DeletedBy   uuid.NullUUID `json:"deleted_by"`
	VersionID   uuid.UUID     `json:"version_id"`
	ContainerID uuid.NullUUID `json:"container_id"`
}

func (q *Queries) SoftDeleteContainerForecastEntry(ctx context.Context, arg SoftDeleteContainerForecastEntryParams) error {
	_, err := q.db.Exec(ctx, softDeleteContainerForecastEntry, arg.DeletedBy, arg.VersionID, arg.ContainerID)
	return err
}

const softDeleteEmployeeForecastEntry = `-- name: SoftDeleteEmployeeForecastEntry :exec
UPDATE forecast_entries
SET
    is_deleted = true,
    deleted_at = now(),
    deleted_by = $1
WHERE version_id  = $2
  AND employee_id = $3
  AND valid_to   IS NULL
  AND is_deleted  = false
`

type SoftDeleteEmployeeForecastEntryParams struct {
	DeletedBy  uuid.NullUUID `json:"deleted_by"`
	VersionID  uuid.UUID     `json:"version_id"`
	EmployeeID uuid.NullUUID `json:"employee_id"`
}

// Removes a planned entry without a hard DELETE.
// The audit trigger fires and logs action = DELETE with the full snapshot.
// The chk_fe_soft_delete constraint ensures deleted_by + deleted_at are set together.
func (q *Queries) SoftDeleteEmployeeForecastEntry(ctx context.Context, arg SoftDeleteEmployeeForecastEntryParams) error {
	_, err := q.db.Exec(ctx, softDeleteEmployeeForecastEntry, arg.DeletedBy, arg.VersionID, arg.EmployeeID)
	return err
}
