// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lookups.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getSystemConfigValue = `-- name: GetSystemConfigValue :one
SELECT value
FROM   system_config
WHERE  key = $1
`

// Fetches a single config value by key.
// Cast to the required type in the application layer.
func (q *Queries) GetSystemConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSystemConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const listClassificationTypes = `-- name: ListClassificationTypes :many


SELECT id, code, label, sort_order
FROM   classification_types
WHERE  is_active = true
ORDER  BY sort_order, label
`

type ListClassificationTypesRow struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	SortOrder int16     `json:"sort_order"`
}

// ============================================================
// queries/lookups.sql
// Lookup tables: classification_types, employee_groups, system_config
// ============================================================
// Returns all active classification types ordered for UI display.
// Result is small (< 20 rows) — no index needed beyond the PK.
func (q *Queries) ListClassificationTypes(ctx context.Context) ([]ListClassificationTypesRow, error) {
	rows, err := q.db.Query(ctx, listClassificationTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListClassificationTypesRow{}
	for rows.Next() {
		var i ListClassificationTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEmployeeGroups = `-- name: ListEmployeeGroups :many
SELECT id, code, label, sort_order
FROM   employee_groups
WHERE  is_active = true
ORDER  BY sort_order, label
`

type ListEmployeeGroupsRow struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	SortOrder int16     `json:"sort_order"`
}

// Returns all active employee groups ordered for UI display.
func (q *Queries) ListEmployeeGroups(ctx context.Context) ([]ListEmployeeGroupsRow, error) {
	rows, err := q.db.Query(ctx, listEmployeeGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEmployeeGroupsRow{}
	for rows.Next() {
		var i ListEmployeeGroupsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Label,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSystemConfig = `-- name: UpsertSystemConfig :exec
INSERT INTO system_config (key, value, description, updated_by, updated_at)
VALUES (
    $1,
    $2,
    $3,
    $4,
    now()
)
ON CONFLICT (key) DO UPDATE
    SET value      = EXCLUDED.value,
        updated_by = EXCLUDED.updated_by,
        updated_at = now()
`

type UpsertSystemConfigParams struct {
	Key         string        `json:"key"`
	Value       string        `json:"value"`
	Description *string       `json:"description"`
	UpdatedBy   uuid.NullUUID `json:"updated_by"`
}

// Creates or updates a config entry.
// updated_by may be NULL for system-level changes (e.g. initial seed).
func (q *Queries) UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) error {
	_, err := q.db.Exec(ctx, upsertSystemConfig,
		arg.Key,
		arg.Value,
		arg.Description,
		arg.UpdatedBy,
	)
	return err
}
