// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

// Extensible lookup for the direct/indirect axis. Extend with INSERT — no ALTER TYPE needed.
type ClassificationType struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	SortOrder int16     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
}

// Self-referential cost-center hierarchy. Walk with WITH RECURSIVE to aggregate FTE up the tree.
type Costcenter struct {
	ID   uuid.UUID `json:"id"`
	Code string    `json:"code"`
	Name string    `json:"name"`
	// 1 = division, 2 = department, 3 = costcenter (leaf). Informational — tree depth is not DB-enforced.
	Level int16 `json:"level"`
	// NULL for root nodes.
	ParentID  uuid.NullUUID      `json:"parent_id"`
	IsActive  bool               `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Thin identity anchor — one row per real SAP employee, ever. All mutable attributes live in employee_actuals or forecast_entries.
type Employee struct {
	ID uuid.UUID `json:"id"`
	// SAP personnel number (Personalnummer). Stable cross-system key — must never be updated.
	EmployeeID string             `json:"employee_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// IMMUTABLE after insert. One row = one employee state for one monthly import run. Never UPDATE or DELETE.
type EmployeeActual struct {
	ID           uuid.UUID `json:"id"`
	ImportRunID  uuid.UUID `json:"import_run_id"`
	EmployeeID   uuid.UUID `json:"employee_id"`
	FirstName    string    `json:"first_name"`
	LastName     string    `json:"last_name"`
	CostcenterID uuid.UUID `json:"costcenter_id"`
	// NULL only if SAP did not supply a value.
	ClassificationID uuid.NullUUID `json:"classification_id"`
	// NULL only if SAP did not supply a value.
	EmployeeGroupID uuid.NullUUID `json:"employee_group_id"`
	JobDescription  *string       `json:"job_description"`
	// Full-time equivalent, e.g. 1.0000 or 0.5000. Always positive for real employees.
	Fte       decimal.Decimal    `json:"fte"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Lookup for the empl_group field. Seed: Executive, Manager, Engineer, Support, Operator.
type EmployeeGroup struct {
	ID        uuid.UUID `json:"id"`
	Code      string    `json:"code"`
	Label     string    `json:"label"`
	SortOrder int16     `json:"sort_order"`
	IsActive  bool      `json:"is_active"`
}

// SCD Type 2. Each attribute change closes the current row (valid_to = change_month) and inserts a new open-ended row (valid_to = NULL).
type ForecastEntry struct {
	ID               uuid.UUID     `json:"id"`
	VersionID        uuid.UUID     `json:"version_id"`
	EmployeeID       uuid.NullUUID `json:"employee_id"`
	ContainerID      uuid.NullUUID `json:"container_id"`
	FirstName        string        `json:"first_name"`
	LastName         string        `json:"last_name"`
	CostcenterID     uuid.UUID     `json:"costcenter_id"`
	ClassificationID uuid.NullUUID `json:"classification_id"`
	EmployeeGroupID  uuid.NullUUID `json:"employee_group_id"`
	JobDescription   *string       `json:"job_description"`
	// Negative = planned reduction (containers only). Greater than 1 = multi-head bucket.
	Fte decimal.Decimal `json:"fte"`
	// Inclusive start — always first day of month, e.g. 2025-04-01.
	ValidFrom pgtype.Date `json:"valid_from"`
	// Exclusive end — first day of superseding month. NULL = currently active row.
	ValidTo   pgtype.Date        `json:"valid_to"`
	IsDeleted bool               `json:"is_deleted"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy uuid.NullUUID      `json:"deleted_by"`
	CreatedBy uuid.UUID          `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// APPEND-ONLY. No UPDATE or DELETE ever. Populated by the audit trigger on forecast_entries (see migration 003).
type ForecastEntryAudit struct {
	ID              uuid.UUID `json:"id"`
	ForecastEntryID uuid.UUID `json:"forecast_entry_id"`
	// Denormalised from forecast_entries for fast per-version audit queries.
	VersionID uuid.UUID `json:"version_id"`
	Action    string    `json:"action"`
	// {"field": {"old": <v>, "new": <v>}}. NULL on INSERT. Full snapshot under "deleted_snapshot" key on DELETE.
	ChangedFields []byte             `json:"changed_fields"`
	ChangedBy     uuid.UUID          `json:"changed_by"`
	ChangedAt     pgtype.Timestamptz `json:"changed_at"`
	ClientIp      *string            `json:"client_ip"`
	UserAgent     *string            `json:"user_agent"`
}

// Version registry. One working version enforced by partial unique index. Archived snapshots are read-only.
type ForecastVersion struct {
	ID          uuid.UUID `json:"id"`
	Label       string    `json:"label"`
	Status      string    `json:"status"`
	PeriodYear  int16     `json:"period_year"`
	PeriodMonth int16     `json:"period_month"`
	// Snapshot of system_config fc_horizon_months at version creation time. Defines how far this version extends.
	FcHorizonMonths int16 `json:"fc_horizon_months"`
	// Self-FK. NULL for the very first version. Forms a singly-linked list for version diffing: working → snapshot_N → snapshot_N-1 → …
	SourceVersionID uuid.NullUUID      `json:"source_version_id"`
	ArchivedAt      pgtype.Timestamptz `json:"archived_at"`
	ArchivedBy      uuid.NullUUID      `json:"archived_by"`
	CreatedBy       uuid.UUID          `json:"created_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

// One row per monthly SAP import. Unique on (period_year, period_month). A re-import requires admin deletion of the prior run first.
type ImportRun struct {
	ID         uuid.UUID `json:"id"`
	PeriodYear int16     `json:"period_year"`
	// 1–12.
	PeriodMonth int16              `json:"period_month"`
	Status      string             `json:"status"`
	RowCount    *int32             `json:"row_count"`
	SourceFile  *string            `json:"source_file"`
	ImportedBy  uuid.UUID          `json:"imported_by"`
	ImportedAt  pgtype.Timestamptz `json:"imported_at"`
}

// Virtual HC buckets with no SAP origin. FTE may be negative (reduction) or >1 (multi-head bucket).
type PlanningContainer struct {
	ID uuid.UUID `json:"id"`
	// Human-readable virtual ID, e.g. "PLAN-CC100-001". Analogous to SAP employee_id.
	EmplPlanNo   string             `json:"empl_plan_no"`
	CostcenterID uuid.UUID          `json:"costcenter_id"`
	Label        string             `json:"label"`
	Notes        *string            `json:"notes"`
	IsActive     bool               `json:"is_active"`
	CreatedBy    uuid.UUID          `json:"created_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// Runtime key/value settings. Cast value to the required type in the application layer.
type SystemConfig struct {
	// Known keys: fc_horizon_months (int), fc_lock_day (int 1-28), import_source_label (string).
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description *string            `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	UpdatedBy   uuid.NullUUID      `json:"updated_by"`
}

// Application users — department heads, planners, admins, readers. Referenced by all audit FK columns.
type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       string             `json:"email"`
	DisplayName string             `json:"display_name"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
