// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Month-over-month delta per costcenter between two import runs.
	// Covers the comparison: "last actual month vs current actual month".
	//
	// Returns one row per costcenter that appears in either run.
	// Rows present only in prev_run_id have curr_fte = NULL (new leaver).
	// Rows present only in curr_run_id have prev_fte = NULL (new joiner).
	//
	// PERFORMANCE NOTE (PG18)
	// Each CTE is a simple aggregation on import_run_id + costcenter_id,
	// hitting idx_employee_actuals_run_cc.  PG18 parallel aggregation can
	// execute both CTEs concurrently when the planner chooses parallel mode.
	// Mark both CTEs MATERIALIZED so the planner runs each exactly once
	// rather than trying to merge them into a single scan.
	ActualsMoMDelta(ctx context.Context, arg ActualsMoMDeltaParams) ([]ActualsMoMDeltaRow, error)
	// Sums FTE and headcount per costcenter for a single import run.
	// Used for the "Actuals" column set in the WebUI table.
	//
	// PLAN: idx_employee_actuals_run_cc (import_run_id, costcenter_id) is a
	// covering index for the GROUP BY — PostgreSQL can aggregate without a
	// heap fetch if the FTE column is included.  If the table grows very large,
	// add INCLUDE (fte) to that index (analogous to migration 004).
	ActualsRollupByCC(ctx context.Context, importRunID uuid.UUID) ([]ActualsRollupByCCRow, error)
	// Transitions the working version to archived.
	// The chk_fv_archived_consistency constraint guarantees that archived_at
	// and archived_by are either both set or both NULL — this UPDATE sets both.
	// Returns the updated row so the caller can record the new archived_at.
	//
	// The WHERE status = 'working' guard prevents accidental double-archiving.
	ArchiveForecastVersion(ctx context.Context, arg ArchiveForecastVersionParams) (ForecastVersion, error)
	// Step 1 for a planning container.
	//
	// PLAN: idx_fe_version_cont_open.
	CloseContainerForecastEntry(ctx context.Context, arg CloseContainerForecastEntryParams) (int64, error)
	// Step 1 of a change for a real employee: close the currently open row.
	// valid_to is the first day of the month when the new state takes effect.
	//
	// Returns the number of rows updated (should always be 0 or 1).
	// If 0 rows updated, no open row exists — the caller should insert without closing.
	//
	// PLAN: idx_fe_version_empl_open (version_id, employee_id)
	// WHERE valid_to IS NULL AND is_deleted = false → single-row key lookup.
	CloseEmployeeForecastEntry(ctx context.Context, arg CloseEmployeeForecastEntryParams) (int64, error)
	// ── Version diff ──────────────────────────────────────────────────────────────
	// Compares total FTE per costcenter between two forecast versions for a
	// single target month.  Returns only costcenters where the values differ.
	//
	// Use cases:
	//   • Compare two archived snapshots (e.g. last month's FC vs this month's FC)
	//   • Compare the working version against the previous snapshot
	//
	// BOTH CTEs are marked MATERIALIZED so the planner executes each exactly
	// once against its respective version_id, using idx_fe_version_cc_from.
	// Without MATERIALIZED, PG12+ may inline the CTEs; while that is safe here,
	// it prevents the parallel execution hint that PG18 uses when both CTEs
	// reference different version_ids (no shared data dependency).
	//
	// PERFORMANCE NOTE (PG18)
	// PG18's improved parallel query infrastructure can run both CTE scans
	// concurrently when max_parallel_workers_per_gather > 0 and the table is
	// large enough to trigger parallelism.  MATERIALIZED makes the independence
	// of the two scans explicit to the planner.
	DiffVersionsByCC(ctx context.Context, arg DiffVersionsByCCParams) ([]DiffVersionsByCCRow, error)
	// Row-level diff between two versions for a given month.
	// Returns every subject (employee or container) where any tracked attribute
	// changed — costcenter_id, classification_id, employee_group_id, or fte.
	//
	// Rows present only in version A (employee left the FC) have *_b columns NULL.
	// Rows present only in version B (employee added to FC) have *_a columns NULL.
	//
	// COALESCE join key: both employee_id and container_id are UUID, but a given
	// subject only appears in one column per row (chk_fe_subject_exclusive).
	// We cast both to TEXT for FULL OUTER JOIN — the cast is cheap, and UUID
	// comparison is always by value so no false matches occur.
	//
	// PLAN: each CTE uses idx_fe_version_empl_from / idx_fe_version_cont_from
	// (from migration 004) for index-only scans on the key columns.
	DiffVersionsByEmployee(ctx context.Context, arg DiffVersionsByEmployeeParams) ([]DiffVersionsByEmployeeRow, error)
	// Same as above for planning containers.
	//
	// PLAN: idx_fe_version_cont_from.
	GetActiveContainerForecastEntry(ctx context.Context, arg GetActiveContainerForecastEntryParams) (GetActiveContainerForecastEntryRow, error)
	// ============================================================
	// queries/forecast_entries.sql
	// SCD Type 2 operations, monthly rollup, and version diff.
	//
	// SCD PATTERN REMINDER
	// ────────────────────
	// Each attribute change is a two-step operation:
	//   1. Close the current open row:  set valid_to = change_month.
	//   2. Insert the new state:        valid_from = change_month, valid_to = NULL.
	//
	// "Active row for month M" predicate (used throughout):
	//   valid_from <= M  AND  (valid_to IS NULL OR valid_to > M)  AND  is_deleted = false
	//
	// Employee and container entries use separate query pairs because the
	// planner can then choose the appropriate partial index (empl vs cont).
	// ============================================================
	// ── Active-row lookups ────────────────────────────────────────────────────────
	// Returns the single active row for a real employee in a given version and month.
	//
	// PLAN: idx_fe_version_empl_from (version_id, employee_id, valid_from)
	// INCLUDE (valid_to, fte, costcenter_id, …) WHERE is_deleted = false.
	// The index leaf page contains all projected columns → index-only scan.
	GetActiveEmployeeForecastEntry(ctx context.Context, arg GetActiveEmployeeForecastEntryParams) (GetActiveEmployeeForecastEntryRow, error)
	// ── Actuals queries ───────────────────────────────────────────────────────────
	// Full history of an employee across all import runs, newest first.
	// Useful for the "employee detail" panel in the WebUI.
	GetActualsForEmployee(ctx context.Context, employeeID uuid.UUID) ([]GetActualsForEmployeeRow, error)
	// ── Audit history ─────────────────────────────────────────────────────────────
	// Full change history for a single forecast_entries row, newest first.
	// Used by the "change history" drawer in the UI.
	GetAuditHistoryForEntry(ctx context.Context, forecastEntryID uuid.UUID) ([]GetAuditHistoryForEntryRow, error)
	// All changes made to a forecast version, newest first.
	// Used by the "version activity log" panel.
	// Limit to a reasonable page size in the application layer.
	GetAuditHistoryForVersion(ctx context.Context, arg GetAuditHistoryForVersionParams) ([]GetAuditHistoryForVersionRow, error)
	GetCostcenterByCode(ctx context.Context, code string) (GetCostcenterByCodeRow, error)
	// ============================================================
	// queries/costcenters.sql
	// Hierarchy traversal and lookup queries for the costcenters table.
	//
	// PERFORMANCE NOTE (PG18)
	// ───────────────────────
	// WITH RECURSIVE queries are executed as a work-table scan in PostgreSQL.
	// PG18 does not change the fundamental recursive CTE execution strategy,
	// but the improved statistics and parallel query infrastructure help when
	// the result set is large.
	//
	// For the typical hierarchy depth (3 levels, < 500 nodes total) these
	// queries are fast regardless of PG version.  If the CC tree grows to
	// thousands of nodes, consider materialising the full ancestry path as a
	// ltree column (pg_catalog extension) to avoid recursion at query time.
	// ============================================================
	GetCostcenterByID(ctx context.Context, id uuid.UUID) (GetCostcenterByIDRow, error)
	// sorts naturally: parent names first, then children alphabetically
	// Returns all active descendants of root_id, including root_id itself.
	// Used to scope a report to a sub-tree (e.g. all CCs under a given department).
	//
	// PLAN: one recursive scan starting from a single row; each step hits
	// idx_costcenters_parent_id.  For a 3-level tree this is at most 3 iterations.
	GetCostcenterDescendants(ctx context.Context, rootID uuid.UUID) ([]GetCostcenterDescendantsRow, error)
	// Returns the full active hierarchy as a flat list, each row annotated
	// with its ancestor path so the UI can reconstruct the tree without a
	// second round-trip.
	//
	// path_ids   — ordered UUID array from root to this node (inclusive)
	// path_names — parallel array of CC names, useful for breadcrumb display
	// depth      — 0-based nesting depth (root = 0)
	//
	// PLAN: anchor scans costcenters on (parent_id IS NULL), then each
	// recursive step uses idx_costcenters_parent_id for a fast index lookup.
	GetCostcenterTree(ctx context.Context) ([]GetCostcenterTreeRow, error)
	GetForecastVersionByID(ctx context.Context, id uuid.UUID) (ForecastVersion, error)
	GetImportRunByID(ctx context.Context, id uuid.UUID) (ImportRun, error)
	// Exact period lookup.  Used before an import to detect duplicate runs.
	GetImportRunByPeriod(ctx context.Context, arg GetImportRunByPeriodParams) (GetImportRunByPeriodRow, error)
	// Returns the most recent successfully completed import.
	// Driving query for "current actual month" comparisons.
	//
	// PLAN: idx_import_runs_status filters to 'completed', then a sort on
	// (period_year DESC, period_month DESC) with LIMIT 1 is cheap because
	// import_runs has at most ~120 rows after 10 years of monthly imports.
	GetLatestCompletedImportRun(ctx context.Context) (GetLatestCompletedImportRunRow, error)
	// Fetches a single config value by key.
	// Cast to the required type in the application layer.
	GetSystemConfigValue(ctx context.Context, key string) (string, error)
	// Walks the source_version_id singly-linked list from a given version
	// back to the root (source_version_id IS NULL).
	// Returns versions oldest-last, i.e. position 1 = the requested version.
	//
	// Use case: render the "version history" sidebar in the WebUI, or list
	// all archived snapshots available for a comparison.
	//
	// PLAN: each recursive step hits idx_fc_versions_source with a single-key
	// lookup.  The chain is at most ~24 nodes for a 2-year rolling forecast,
	// so this is always fast.
	//
	// PERFORMANCE NOTE (PG18)
	// MATERIALIZED is intentional: without it, PG12+ may try to inline the
	// recursive CTE into the outer query.  Inlining a recursive CTE is not
	// possible today, but the hint future-proofs the query against planner
	// changes and makes the intent explicit.
	GetVersionChain(ctx context.Context, startVersionID uuid.UUID) ([]GetVersionChainRow, error)
	// ============================================================
	// queries/forecast_versions.sql
	// Version lifecycle management: create, archive, seed, diff chain.
	// ============================================================
	// There is at most one working version at any time (partial unique index
	// uq_fc_versions_one_working enforces this at the DB level).
	// Returns an error if no working version exists yet.
	//
	// PLAN: index scan on idx_fc_versions_status, then LIMIT 1.
	GetWorkingForecastVersion(ctx context.Context) (GetWorkingForecastVersionRow, error)
	// ── employee_actuals insert (called in bulk via CopyFrom at import time) ──────
	// Single-row variant used for testing and small corrections.
	// For production imports, use pgx CopyFrom for bulk inserts instead.
	InsertEmployeeActual(ctx context.Context, arg InsertEmployeeActualParams) (EmployeeActual, error)
	// ── SCD Type 2 write operations ───────────────────────────────────────────────
	// Step 2 of a change: insert the new attribute state.
	// valid_to is NULL for the new open-ended row.
	// Always pair with CloseEmployee/ContainerForecastEntry (step 1) unless
	// this is the very first entry for the subject in this version.
	InsertForecastEntry(ctx context.Context, arg InsertForecastEntryParams) (ForecastEntry, error)
	// Creates a new working version.
	// source_version_id is NULL only for the very first version ever created;
	// in all subsequent months it points to the just-archived snapshot.
	InsertForecastVersion(ctx context.Context, arg InsertForecastVersionParams) (ForecastVersion, error)
	// ============================================================
	// queries/actuals.sql
	// SAP/Excel import tracking and employee_actuals queries.
	//
	// All employee_actuals rows are IMMUTABLE after insert.
	// There are no UPDATE or DELETE queries in this file by design.
	// ============================================================
	// ── Import run management ─────────────────────────────────────────────────────
	InsertImportRun(ctx context.Context, arg InsertImportRunParams) (ImportRun, error)
	// Flat list of all active CCs ordered by level then code.
	// Used to populate dropdowns; no hierarchy traversal needed.
	ListActiveCostcenters(ctx context.Context) ([]ListActiveCostcentersRow, error)
	// All active entries (employees + containers) in a version for a given month.
	// Used to seed the next working version at month rollover.
	//
	// PLAN: idx_fe_version_valid_from (version_id, valid_from) for the range scan;
	// heap access for the remaining columns.  For the seed operation this full
	// scan is expected and unavoidable — it runs once per month.
	ListActiveEntriesForVersion(ctx context.Context, arg ListActiveEntriesForVersionParams) ([]ListActiveEntriesForVersionRow, error)
	// ============================================================
	// queries/lookups.sql
	// Lookup tables: classification_types, employee_groups, system_config
	// ============================================================
	// Returns all active classification types ordered for UI display.
	// Result is small (< 20 rows) — no index needed beyond the PK.
	ListClassificationTypes(ctx context.Context) ([]ListClassificationTypesRow, error)
	// Returns all active employee groups ordered for UI display.
	ListEmployeeGroups(ctx context.Context) ([]ListEmployeeGroupsRow, error)
	// All versions newest-first.  Used for the version picker in the WebUI.
	ListForecastVersions(ctx context.Context) ([]ListForecastVersionsRow, error)
	// Full history, newest first.
	ListImportRuns(ctx context.Context) ([]ListImportRunsRow, error)
	// ── Monthly rollup (WebUI table — the most critical query) ────────────────────
	// Returns total FTE and headcount per costcenter per month for a version.
	// This drives the main WebUI table: rows = costcenters, columns = months.
	//
	// PARAMETERS
	//   version_id     — which forecast version to read
	//   fc_start_month — first month of the grid  (first day of month, e.g. 2025-01-01)
	//   fc_end_month   — last  month of the grid  (first day of month, e.g. 2026-06-01)
	//
	// QUERY STRATEGY
	// generate_series produces one row per month.  The CROSS JOIN LATERAL
	// tells the planner to execute the subquery independently for each month
	// value, which allows index-only scans on idx_fe_version_cc_from for each
	// (version_id, *, valid_from) prefix.
	//
	// Without LATERAL the planner might choose a hash join across all months
	// simultaneously, which forces a full scan of forecast_entries for the
	// version — far more expensive when only the last few months have changes.
	//
	// PERFORMANCE NOTE (PG18)
	// ───────────────────────
	// idx_fe_version_cc_from (from migration 004) now includes valid_to and fte
	// via INCLUDE, making this a fully index-only scan — no heap access at all.
	//
	// PG18 async I/O reduces heap-fetch latency when the index is cold (first
	// query after restart).  For warm-cache production queries the INCLUDE
	// strategy is what matters most.
	//
	// headcount counts all rows (including containers with FTE > 1 or < 0).
	// If you want headcount to count only positive-FTE employees, add a WHERE
	// clause inside the subquery: AND fte > 0 AND employee_id IS NOT NULL.
	MonthlyForecastRollupByCC(ctx context.Context, arg MonthlyForecastRollupByCCParams) ([]MonthlyForecastRollupByCCRow, error)
	SoftDeleteContainerForecastEntry(ctx context.Context, arg SoftDeleteContainerForecastEntryParams) error
	// Removes a planned entry without a hard DELETE.
	// The audit trigger fires and logs action = DELETE with the full snapshot.
	// The chk_fe_soft_delete constraint ensures deleted_by + deleted_at are set together.
	SoftDeleteEmployeeForecastEntry(ctx context.Context, arg SoftDeleteEmployeeForecastEntryParams) error
	// Called after the bulk insert of employee_actuals to record the final count.
	UpdateImportRunRowCount(ctx context.Context, arg UpdateImportRunRowCountParams) error
	// Creates or updates a config entry.
	// updated_by may be NULL for system-level changes (e.g. initial seed).
	UpsertSystemConfig(ctx context.Context, arg UpsertSystemConfigParams) error
}

var _ Querier = (*Queries)(nil)
